name = input("what is your name?")
print(f"Hello {name}! Nice to meet you!\n")
name = input("what is your name?")
print(f"Hello {name}! Nice to meet you!\n")
city = input("Which city do you live in? ")
hobby = input("What's your favorite hobby? ")
print(f"Lives in: {city}")
print(f"Favorite hobby: {hobby}")
data = input("Enter name, age, city: ")
name, age, city = data.split()
print(data)
